import {describe,it,expect} from 'vitest';
import {calendarDays,pacificDay,taskReady,valueContributions,dayMetrics,type Task,type WorkRecord,type Workspace} from '../model';
const task:Task={id:'task',job_id:'job',description:'Shared flat work',item_code:'TEST',pricing_method:'flat',amount:950,service_value:950,quantity:1,approved:true};
const record=(id:string,technician:string,date:string,minutes:number,progress:WorkRecord['progress']='done'):WorkRecord=>({id,task_id:'task',visit_id:null,technician,work_date:date,minutes,progress,note:'',materials:'',status:'reviewed',review_note:'',review_owner:'office',version:1});
describe('performed-date billing attribution',()=>{
 it('allocates one flat fee across multiple technicians and days, without multiplying it',()=>{const rs=[record('1','Alberto','2026-09-14',120,'partial'),record('2','Brody','2026-09-15',60)];expect(valueContributions(task,rs)).toEqual([{technician:'Alberto',day:'2026-09-14',value:633.33},{technician:'Brody',day:'2026-09-15',value:316.67}]);});
 it('does not recognize partially done or unreviewed work as earned',()=>{expect(valueContributions(task,[record('1','Alberto','2026-09-14',120,'partial')])).toEqual([]);expect(taskReady(task,[{...record('1','Alberto','2026-09-14',120),status:'held'}])).toBe(false);});
 it('keeps actual time, materials, draft value and equivalent hours separate',()=>{const data={jobs:[],visits:[],staff:[],targets:[],office:true,person:'Alberto',tasks:[task],records:[record('1','Alberto','2026-09-14',420)],allocations:[{task_id:'task',invoice_id:'inv',amount:950,service_value:950,benchmark:95}],invoices:[{id:'inv',invoice_code:'INV',status:'draft',maintenance_job_id:'job',total_amount:1000}]} satisfies Workspace;expect(dayMetrics(data,'Alberto','2026-09-14')).toMatchObject({actual:7,completed:950,draft:950,issued:0,equivalent:10,unbilled:0});data.invoices[0].status='generated';expect(dayMetrics(data,'Alberto','2026-09-14')).toMatchObject({actual:7,completed:950,draft:0,issued:950});});
 it('uses Pacific service dates and Monday weeks across month boundaries',()=>{expect(pacificDay(new Date('2026-09-19T01:00:00Z'))).toBe('2026-09-18');expect(calendarDays('2026-03-01','week')[0]).toBe('2026-02-23');expect(calendarDays('2028-02-15','month')).toHaveLength(29);});
});
