'use client';
import {useState} from 'react';
import type {HdmsInvoice} from '@/lib/invoices';
export function WorkspaceInvoice({invoice,onBack,onSaved}:{invoice:HdmsInvoice;onBack:()=>void;onSaved:(i:HdmsInvoice)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
 async function generate(){setBusy(true);setError('');try{const r=await fetch(`/api/invoices/${invoice.id}/generate-pdf`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);onSaved(d.invoice);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-xl border bg-white p-6"><button className="min-h-11 underline" onClick={onBack}>Back to invoices</button><h2 className="text-2xl font-semibold">{invoice.invoice_code}</h2><p>{invoice.property_name} · {invoice.status}</p><p className="rounded-lg bg-green-50 p-3 text-sm">These charges come from reviewed work records. Manage scope and draft allocations in the <a className="underline" href="/maintenance/workspace?view=billing">maintenance workspace</a>.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<ul className="divide-y">{invoice.line_items?.map((l,i)=><li className="flex justify-between gap-4 py-3" key={i}><span>{l.description}</span><b>{money(l.amount)}</b></li>)}</ul><p className="text-xl font-semibold">Total {money(invoice.total_amount)}</p><div className="flex gap-3">{invoice.status==='draft'&&<button className="min-h-11 rounded-lg bg-green-900 px-4 text-white" disabled={busy} onClick={generate}>{busy?'Generating…':'Generate invoice PDF'}</button>}{invoice.pdf_path&&<a className="underline p-3" href={`/api/invoices/${invoice.id}/download`} target="_blank" rel="noreferrer">Download PDF</a>}</div><p className="text-xs text-gray-500">Partial drafts can stay open. Issuing before all scope is billed requires recorded progress-billing authorization in the job.</p></section>;
}
