'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {CalendarDays,ClipboardList,Clock,FileText,Plus,RefreshCw,ArrowLeft} from 'lucide-react';
import {calendarDays,dayMetrics,pacificDay,shiftDay,taskReady,type Workspace,type Job,type Task,type Visit,type WorkRecord} from '@/lib/maintenance-workspace/model';
import type {PriceBookItem} from '@/lib/turn-estimator/types';
import './workspace.css';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const time=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const input=(form:FormData,key:string)=>String(form.get(key)||'');
type Editor={kind:'job'|'task'|'visit'|'record'|'target';job?:Job;task?:Task;visit?:Visit;record?:WorkRecord;clientId?:string};
export default function MaintenanceWorkspace({field=false}:{field?:boolean}){
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('today'),[day,setDay]=useState(pacificDay()),[mode,setMode]=useState<'day'|'week'|'month'>('week'),[filter,setFilter]=useState(''),[person,setPerson]=useState(''),[jobId,setJobId]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[items,setItems]=useState<PriceBookItem[]>([]),[drafts,setDrafts]=useState<{id:string;payload:{propertyName:string;unitName:string};updated_at:string}[]>([]),[orders,setOrders]=useState<{id:string;property_name:string;wo_number:string;description:string}[]>([]),[search,setSearch]=useState(''),[note,setNote]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]);
 const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/maintenance/workspace');const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');if(d.office&&!field){const [p,s]=await Promise.all([fetch('/api/turn-estimator/price-book'),fetch('/api/turn-estimator/saved-drafts')]);const prices=await p.json(),saved=await s.json();setItems(prices.items||[]);setDrafts(saved.drafts||[]);}}catch(e){setError((e as Error).message);}},[field]);
 useEffect(()=>{load();const view=new URLSearchParams(window.location.search).get('view');if(view)setTab(view);},[load]);
 async function mutate(body:Record<string,unknown>,close=true){setBusy(true);setError('');try{const r=await fetch('/api/maintenance/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);if(close)setEditor(null);await load();setNotice('Saved');return d.result;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 const office=!!data?.office&&!field;
 const jobs=data?.jobs.filter(j=>!filter||`${j.property_name} ${j.unit_name} ${j.title}`.toLowerCase().includes(filter.toLowerCase()))||[];
 const job=data?.jobs.find(j=>j.id===jobId);
 const tasks=data?.tasks.filter(t=>t.job_id===jobId)||[];
 const people=data?.staff.filter(p=>!person||p.person===person)||[];
 function openJob(jid:string){setJobId(jid);setSelected([]);setTab('job');}
 async function searchOrders(){setBusy(true);try{const r=await fetch(`/api/work-orders?search=${encodeURIComponent(search)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setOrders(d.workOrders||[]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submitForm(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editor||!data||busy)return;const f=new FormData(e.currentTarget),val=(k:string)=>input(f,k);let b:Record<string,unknown>={};
  if(editor.kind==='visit'){const hh=val('start').split(':').map(Number);b={op:'visit',job_id:editor.job!.id,id:editor.visit?.id,version:editor.visit?.version,technicians:f.getAll('technicians'),work_date:val('date'),start_minute:hh[0]*60+hh[1],planned_minutes:Number(val('minutes')),note:val('note'),status:val('status')||'planned'};}
  if(editor.kind==='task')b={op:'task',job_id:editor.job!.id,item_code:val('item_code'),qty:Number(val('qty')),minutes:val('minutes')?Number(val('minutes')):undefined,est_material_cost:Number(val('cost')||0),description:val('description'),approval_note:val('approval_note'),in_house:f.get('in_house')==='on'};
  if(editor.kind==='record')b={op:val('action')||'submit',id:editor.record?.id||editor.clientId,version:editor.record?.version||0,task_id:editor.task!.id,technician:val('technician')||data.person,visit_id:editor.record?.visit_id||null,work_date:val('date'),minutes:Number(val('minutes')),progress:val('progress'),note:val('note'),materials:val('materials')};
  if(editor.kind==='target')b={op:'target',technician:val('technician'),effective_from:val('date'),benchmark:Number(val('benchmark')),min_hours:Number(val('min')),max_hours:Number(val('max'))};
  await mutate(b);
 }
 function recordCard(r:WorkRecord){const t=data!.tasks.find(t=>t.id===r.task_id),j=data!.jobs.find(j=>j.id===t?.job_id);return <article className="mw-card" key={r.id}><div className="mw-between"><strong>{j?.property_name} · {t?.description}</strong><span className={`mw-tag ${r.status==='held'||r.status==='returned'?'amber':''}`}>{r.status}</span></div><p>{r.technician} · {r.work_date} · {r.minutes} min actual · {r.progress}</p><p>{r.note}</p>{r.materials&&<p><b>Materials to review:</b> {r.materials}</p>}{r.review_note&&<p className="mw-callout">{r.review_owner}: {r.review_note}</p>}
 {office&&['submitted','held'].includes(r.status)&&<div className="mw-stack"><label>Review note / question<input value={note[r.id]||''} onChange={e=>setNote({...note,[r.id]:e.target.value})}/></label><div className="mw-actions">{(['reviewed','held','returned'] as const).map(status=><button key={status} disabled={busy} onClick={()=>mutate({op:'review',id:r.id,version:r.version,status,note:note[r.id]||''},false)}>{status==='reviewed'?'Accept work':status==='held'?'Hold':'Return question'}</button>)}</div></div>}
 {['draft','returned'].includes(r.status)&&t&&<button onClick={()=>setEditor({kind:'record',task:t,record:r})}>Continue work record</button>}</article>;}
 return <main className={`mw ${field?'mw-field':''}`}><header className="mw-header"><div><p className="mw-eyebrow">HDPM {field?'FIELD':'MAINTENANCE'}</p><h1>{field?'Your workday':'Work, schedule & billing'}</h1><p>{field?'Record the work. Keep your day accounted for.':'See what happened, what is planned, and what needs billing.'}</p></div><div className="mw-actions"><button aria-label="Refresh workspace" onClick={load}><RefreshCw size={18}/></button>{office&&<Link href="/maintenance/invoices">Invoices & reconciliation</Link>}<Link href={field?'/timekeeping':'/maintenance/field'}>{field?'Payroll timecard':'Technician view'}</Link></div></header>
 <nav className="mw-nav">{(field?[['today','My Day',Clock],['jobs','Jobs',ClipboardList],['time','My Time',FileText]]:[['today','Today',Clock],['schedule','Schedule',CalendarDays],['jobs','Jobs & Estimates',ClipboardList],['billing','Billing',FileText]]).map(([id,label,Icon])=>{const I=Icon as typeof Clock;return <button key={String(id)} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(String(id));setJobId('');}}><I size={18}/>{String(label)}</button>;})}</nav>
 {error&&<div role="alert" className="mw-error">{error}<button onClick={load}>Retry</button></div>}{notice&&<p role="status" className="mw-saved">{notice}</p>}
 {!data?<div className="mw-card">{error?'The workspace could not load. Its database migration may still need to be applied.':'Loading your workspace…'}</div>:<>
 {tab!=='job'&&<div className="mw-filters"><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value||pacificDay())}/></label>{office&&<label>Technician<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">All staff</option>{data.staff.map(p=><option key={p.person}>{p.person}</option>)}</select></label>}<label>Property / job<input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter jobs"/></label></div>}
 {tab==='today'&&<>
 {office&&<div className="mw-grid">{people.filter(p=>data.records.some(r=>r.technician===p.person&&r.work_date===day)||data.visits.some(v=>v.technicians.includes(p.person)&&v.work_date===day)||['Alberto','Brody'].includes(p.person)).map(p=>{const m=dayMetrics(data,p.person,day);return <article className="mw-card" key={p.person}><h2>{p.person}</h2><div className="mw-number">{m.actual.toFixed(1)} <small>actual hours</small></div><p>{money(m.completed)} completed service · {m.equivalent.toFixed(1)} equivalent hours</p><p>Target {money(Number(m.target.benchmark)*Number(m.target.min_hours))}–{money(Number(m.target.benchmark)*Number(m.target.max_hours))}</p><div className="mw-callout">Draft {money(m.draft)} · Issued {money(m.issued)} · Unbilled {money(m.unbilled)}{m.voided>0&&` · Voided ${money(m.voided)}`}</div></article>;})}</div>}
 <div className="mw-between"><h2>{day===pacificDay()?"Today's visits":'Scheduled visits'}</h2>{office&&<button onClick={()=>{setTab('jobs');setNotice('Open a job to schedule its next visit.');}}><Plus size={16}/>Schedule work</button>}</div>
 <div className="mw-grid">{data.visits.filter(v=>v.work_date===day&&v.status!=='cancelled'&&(!person||v.technicians.includes(person))&&jobs.some(j=>j.id===v.job_id)).sort((a,b)=>a.start_minute-b.start_minute).map(v=><button className="mw-card mw-job" key={v.id} onClick={()=>openJob(v.job_id)}><span className="mw-tag">{time(v.start_minute)} · {v.planned_minutes} min planned</span><h2>{data.jobs.find(j=>j.id===v.job_id)?.property_name}</h2><p>{v.technicians.join(', ')} · {v.status}</p><small>Local plan</small></button>)}</div>
 {!data.visits.some(v=>v.work_date===day&&v.status!=='cancelled')&&<p className="mw-empty">No visits planned for this date. Open a job to assign the next visit.</p>}
 <h2>{office?'Needs attention':'Your unfinished updates & office questions'}</h2><div className="mw-stack">{data.records.filter(r=>office?['submitted','held','returned'].includes(r.status):['draft','returned'].includes(r.status)).map(recordCard)}</div>
 {office&&<><h2>Completed service awaiting a draft</h2>{data.tasks.filter(t=>taskReady(t,data.records)&&!data.allocations.some(a=>a.task_id===t.id)).map(t=><button className="mw-card mw-job" key={t.id} onClick={()=>openJob(t.job_id)}>{data.jobs.find(j=>j.id===t.job_id)?.property_name} · {t.description} · {money(Number(t.amount))}</button>)}<h2>Missing work records</h2>{data.visits.filter(v=>v.work_date<day&&v.status!=='cancelled'&&!data.records.some(r=>r.visit_id===v.id||data.tasks.some(t=>t.id===r.task_id&&t.job_id===v.job_id)&&r.work_date===v.work_date&&v.technicians.includes(r.technician))).map(v=><button key={v.id} className="mw-card mw-job" onClick={()=>openJob(v.job_id)}>{v.work_date} · {data.jobs.find(j=>j.id===v.job_id)?.property_name} · {v.technicians.join(', ')}</button>)}</>}
 <p className="mw-footnote">Actual job time is separate from payroll. Completed service value excludes materials and coordination; draft and issued values are portions of it. Credits and payment reconciliation remain in the invoice tools.</p>
 </>}
 {tab==='schedule'&&<><div className="mw-actions"><button onClick={()=>setDay(shiftDay(day,mode==='month'?-28:mode==='week'?-7:-1))}>Previous</button>{(['day','week','month'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='day'?'Day':m==='week'?'Week':'Month'}</button>)}<button onClick={()=>setDay(shiftDay(day,mode==='month'?28:mode==='week'?7:1))}>Next</button></div><div className="mw-calendar" style={{gridTemplateColumns:`140px repeat(${calendarDays(day,mode).length}, minmax(170px,1fr))`}}><b>Technician</b>{calendarDays(day,mode).map(d=><b key={d}>{new Date(`${d}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}</b>)}{people.map(p=><div className="mw-calendar-row" key={p.person}><strong>{p.person}</strong>{calendarDays(day,mode).map(d=>{const m=dayMetrics(data,p.person,d);return <div key={d} className={d===pacificDay()?'mw-calendar-today':''}>{data.visits.filter(v=>v.work_date===d&&v.technicians.includes(p.person)&&v.status!=='cancelled'&&jobs.some(j=>j.id===v.job_id)).map(v=><button className="mw-calendar-visit" key={v.id} onClick={()=>{const j=data.jobs.find(j=>j.id===v.job_id);setEditor({kind:'visit',job:j,visit:v});}}><b>{time(v.start_minute)} {data.jobs.find(j=>j.id===v.job_id)?.property_name}</b><small>{v.planned_minutes} min · {v.status} · local plan</small></button>)}{m.actual>0&&<button className="mw-calendar-actual" onClick={()=>{setDay(d);setPerson(p.person);setTab('time');}}>{m.actual.toFixed(1)}h actual<br/>{money(m.completed)} service<br/>Draft {money(m.draft)} · Issued {money(m.issued)}</button>}</div>;})}</div>)}</div><h2>Unscheduled jobs</h2><div className="mw-grid">{jobs.filter(j=>!data.visits.some(v=>v.job_id===j.id&&v.status==='planned'&&v.work_date>=day)).map(j=><button key={j.id} className="mw-card mw-job" onClick={()=>setEditor({kind:'visit',job:j})}>{j.property_name} · {j.title}</button>)}</div><p className="mw-footnote">Moving a visit changes the plan only. Recorded work dates stay unchanged. AppFolio's schedule is available from the original work order; local plans are not written back.</p></>}
 {tab==='jobs'&&<><div className="mw-between"><h2>Jobs & scope</h2>{office&&<div className="mw-actions"><button onClick={()=>setEditor({kind:'job'})}><Plus size={16}/>Add work order</button><Link href="/turn-estimator/estimates/new">New estimate / templates</Link><Link href="/turn-estimator/price-book">Price book</Link></div>}</div><div className="mw-grid">{jobs.map(j=><button key={j.id} className="mw-card mw-job" onClick={()=>openJob(j.id)}><h2>{j.property_name}{j.unit_name?` · ${j.unit_name}`:''}</h2><p>{j.title}</p><span className="mw-tag">{data.tasks.filter(t=>t.job_id===j.id).length} tasks</span></button>)}</div>{!jobs.length&&<div className="mw-empty">{office?'Add an existing work order to start tracking its scope, visits and billing.':'Your assigned jobs will appear here when the office schedules a visit.'}</div>}{office&&<><h2>Saved estimate drafts</h2><div className="mw-grid">{drafts.map(d=><Link className="mw-card" key={d.id} href={`/turn-estimator/estimates/new?resume=${d.id}`}><h3>{d.payload.propertyName||'Untitled estimate'}</h3><p>{d.payload.unitName} · Saved {new Date(d.updated_at).toLocaleString()}</p>Continue estimate</Link>)}</div></>}</>}
 {tab==='job'&&job&&<><button onClick={()=>setTab('jobs')}><ArrowLeft size={18}/>All jobs</button><header className="mw-job-header"><h1>{job.property_name} {job.unit_name}</h1><p>{job.property_address}</p><h2>{job.title}</h2></header>{office&&<div className="mw-actions"><button onClick={()=>setEditor({kind:'task',job})}>Add priced task</button><button onClick={()=>setEditor({kind:'visit',job})}>Schedule visit</button><Link href={`/turn-estimator/estimates/new?from_wo=${job.work_order_id}`}>Create estimate</Link><Link href={`/maintenance/board/wo/${job.work_order_id}`}>Original work order</Link><button onClick={async()=>{setBusy(true);try{const r=await fetch(`/api/turn-estimator/estimates?work_order_id=${job.work_order_id}`);const d=await r.json();const e=d.estimates?.find((e:{status:string})=>e.status==='approved');if(!e)throw new Error('No approved estimate found for this work order');await mutate({op:'import_estimate',job_id:job.id,estimate_id:e.id});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Import approved scope</button></div>}
 <h2>Scope & completion</h2><div className="mw-stack">{tasks.map(t=>{const a=data.allocations.find(a=>a.task_id===t.id);return <article key={t.id} className="mw-card"><div className="mw-between"><h3>{t.description}</h3>{office&&<strong>{money(Number(t.amount))}</strong>}</div><p>{t.quantity} units · {a?'In billing':taskReady(t,data.records)?'Reviewed & complete':'Work remaining'}</p>{office&&!a&&<label className="mw-check"><input type="checkbox" checked={selected.includes(t.id)} disabled={!taskReady(t,data.records)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(id=>id!==t.id))}/>Include completed task in draft</label>}{!a&&<button onClick={()=>setEditor({kind:'record',task:t,clientId:crypto.randomUUID()})}>Record work</button>}</article>;})}</div>{office&&<div className="mw-actions"><button className="mw-primary" disabled={!selected.length||busy} onClick={()=>mutate({op:'billing',job_id:job.id,task_ids:selected}).then(r=>{if(r){setSelected([]);setNotice(`Draft ${r.invoice_code} prepared`);}})}>Add selected tasks to rolling draft</button><label className="mw-check"><input type="checkbox" checked={job.progress_billing} onChange={e=>{if(!e.target.checked)mutate({op:'job_settings',job_id:job.id,progress_billing:false,approval_note:''});else setNotice('Enter the owner authorization below, then enable progress billing.');}}/>Progress billing authorized</label></div>}{office&&!job.progress_billing&&<form className="mw-actions" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate({op:'job_settings',job_id:job.id,progress_billing:true,approval_note:input(f,'authorization')});}}><input aria-label="Progress billing authorization" name="authorization" required placeholder="Who authorized progress billing, and when?"/><button>Enable progress billing</button></form>}
 <h2>Work history</h2><div className="mw-stack">{data.records.filter(r=>tasks.some(t=>t.id===r.task_id)).map(recordCard)}</div><h2>Visits</h2>{data.visits.filter(v=>v.job_id===job.id).map(v=><article key={v.id} className="mw-card"><div className="mw-between"><span>{v.work_date} · {time(v.start_minute)} · {v.technicians.join(', ')} · {v.status}</span>{office&&<button onClick={()=>setEditor({kind:'visit',job,visit:v})}>Edit plan</button>}</div></article>)}
 </>}
 {tab==='billing'&&<><h2>Review completed work</h2><div className="mw-stack">{data.records.filter(r=>['submitted','held'].includes(r.status)&&(!person||r.technician===person)&&jobs.some(j=>data.tasks.some(t=>t.job_id===j.id&&t.id===r.task_id))).map(recordCard)}</div><h2>Ready to draft</h2>{data.tasks.filter(t=>taskReady(t,data.records)&&!data.allocations.some(a=>a.task_id===t.id)).map(t=><button key={t.id} className="mw-card mw-job" onClick={()=>openJob(t.job_id)}>{data.jobs.find(j=>j.id===t.job_id)?.property_name} · {t.description} · {money(Number(t.amount))}</button>)}<h2>Drafts & issued invoices</h2><div className="mw-grid">{data.invoices.map(i=><article className="mw-card" key={i.id}><span className="mw-tag">{i.status}</span><h3>{i.invoice_code}</h3><p>{data.jobs.find(j=>j.id===i.maintenance_job_id)?.property_name} · {money(Number(i.total_amount))}</p><Link href={`/maintenance/invoices?invoice=${i.id}`}>Open invoice tools</Link>{i.status==='draft'&&<button disabled={busy} onClick={()=>mutate({op:'release',job_id:i.maintenance_job_id,invoice_id:i.id})}>Release unissued draft</button>}</article>)}</div><p className="mw-footnote">Releasing a draft voids it and makes its tasks available again. Issued or voided billing stays reserved for correction review; it is not automatically charged again.</p><button onClick={()=>setEditor({kind:'target'})}>Configure technician target</button></>}
 {tab==='time'&&<><h2>Actual work on {day}</h2><div className="mw-stack">{data.records.filter(r=>r.work_date===day&&(!person||r.technician===person)).map(recordCard)}</div><p className="mw-callout">Job records explain work performed. Travel, breaks and other time belong on the payroll timecard. Flat-fee equivalents are never payroll hours.</p></>}
 </>}
 {editor&&data&&<div className="mw-overlay"><section className="mw-dialog" role="dialog" aria-modal="true" aria-labelledby="editor-title"><div className="mw-between"><h2 id="editor-title">{editor.kind==='job'?'Add a work order':editor.kind==='task'?'Add approved scope':editor.kind==='visit'?'Schedule a visit':editor.kind==='target'?'Daily service target':'Record work performed'}</h2><button onClick={()=>setEditor(null)}>Close</button></div>{error&&<div role="alert" className="mw-error">{error}</div>}
 {editor.kind==='job'?<><label>Find property or work order<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button disabled={busy} onClick={searchOrders}>Search work orders</button><div className="mw-stack">{orders.map(o=><button key={o.id} className="mw-card mw-job" disabled={busy} onClick={()=>mutate({op:'job',work_order_id:o.id}).then(j=>{if(j)openJob(j.id);})}><b>{o.property_name} · {o.wo_number}</b><p>{o.description}</p></button>)}</div></>:<form className="mw-stack" onSubmit={submitForm}>
 {editor.kind==='task'&&<><label>Price-book item<select name="item_code" required><option value="">Choose approved pricing</option>{items.map(i=><option key={i.id} value={i.item_code} disabled={/placeholder/i.test(i.name)}>{i.name} · {i.pricing_method}</option>)}</select></label><label>Job-specific description<input name="description" placeholder="Leave blank to use the price-book description"/></label><div className="mw-filters"><label>Quantity<input name="qty" type="number" min="0.01" step="0.01" defaultValue="1" required/></label><label>Priced minutes (hourly/minimum)<input name="minutes" type="number" min="0"/></label><label>Material/vendor cost<input name="cost" type="number" min="0" step="0.01"/></label></div><label className="mw-check"><input type="checkbox" name="in_house" defaultChecked/>In-house service (uncheck for outside-vendor work)</label><label>Scope and charge authorization<textarea name="approval_note" required placeholder="Approved scope, responsible payer, approver and date"/></label><p className="mw-footnote">Prices are resolved on the server from the current price book. Materials described by a technician require a separate office-reviewed scope item.</p></>}
 {editor.kind==='visit'&&<><label>Planned date<input name="date" type="date" defaultValue={editor.visit?.work_date||day} required/></label><div className="mw-filters"><label>Start time (Pacific)<input name="start" type="time" defaultValue={time(editor.visit?.start_minute??510)} required/></label><label>Planned minutes<input name="minutes" type="number" min="1" max="960" defaultValue={editor.visit?.planned_minutes||60} required/></label></div><fieldset><legend>Technicians</legend>{data.staff.map(p=><label key={p.person} className="mw-check"><input type="checkbox" name="technicians" value={p.person} defaultChecked={editor.visit?.technicians.includes(p.person)||false}/>{p.name||p.person}</label>)}</fieldset><label>Status<select name="status" defaultValue={editor.visit?.status||'planned'}><option value="planned">Planned</option><option value="complete">Visit complete</option><option value="cancelled">Cancelled</option></select></label><label>Visit notes<textarea name="note" defaultValue={editor.visit?.note}/></label></>}
 {editor.kind==='record'&&<><p>{editor.task?.description}</p><label>Technician<select name="technician" defaultValue={editor.record?.technician||data.person} disabled={!!editor.record}>{data.staff.map(p=><option key={p.person} value={p.person}>{p.name||p.person}</option>)}</select>{editor.record&&<input type="hidden" name="technician" value={editor.record.technician}/>}</label><label>Date worked<input name="date" type="date" max={pacificDay()} defaultValue={editor.record?.work_date||pacificDay()} required/></label><label>Actual minutes on this task<input name="minutes" type="number" min="1" max="960" defaultValue={editor.record?.minutes} required/></label><label>Task progress<select name="progress" defaultValue={editor.record?.progress||'done'}><option value="done">Done</option><option value="partial">Part done</option><option value="blocked">Blocked</option></select></label><label>Work notes<textarea name="note" defaultValue={editor.record?.note} placeholder="What was completed, or what still needs attention?"/></label><label>Materials used / evidence notes<textarea name="materials" defaultValue={editor.record?.materials} placeholder="Parts, quantities, receipt or evidence reference for office review"/></label><label>Save or submit<select name="action" defaultValue="submit"><option value="submit">Submit for office review</option><option value="record">Save unfinished record</option></select></label></>}
 {editor.kind==='target'&&<><label>Technician<select name="technician">{data.staff.map(p=><option key={p.person}>{p.person}</option>)}</select></label><label>Effective from<input type="date" name="date" defaultValue={day} required/></label><label>Service benchmark ($/hour)<input name="benchmark" type="number" min="1" step="0.01" defaultValue="95" required/></label><label>Minimum equivalent hours<input name="min" type="number" min="0" step="0.1" defaultValue="6" required/></label><label>Maximum equivalent hours<input name="max" type="number" min="0" step="0.1" defaultValue="8" required/></label><p>Use 0–0 for a day off, and add a later effective date to restore the regular target. Historical target rows are retained.</p></>}
 <button className="mw-primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form>}</section></div>}
 </main>;
}
