export interface TemplateEntry { item_code:string; description:string; qty:string; minutes:string; material_cost:string; room:string; included:boolean }
export interface EstimateTemplate { id:string; family_id:string; name:string; version:number; entries:TemplateEntry[]; archived:boolean }
const entry=(description:string,item_code='',included=false,minutes=''):TemplateEntry=>({description,item_code,included,qty:'1',minutes,material_cost:'',room:''});
export const STARTER_TEMPLATES:EstimateTemplate[]=[
 {id:'starter-turn',family_id:'starter-turn',name:'Standard unit turn',version:1,archived:false,entries:[entry('Inspection and scope','TURN_INSPECT',true),entry('Maintenance punch list','LABOR_STD',false,'60'),entry('Full turn cleaning','CLEAN_STD'),entry('Paint / touch-up','PAINT_WALL'),entry('Flooring and carpet review'),entry('Locks and keys'),entry('Smoke / CO and safety checks'),entry('Appliance inspection'),entry('Haul-away','HAUL_LOAD'),entry('Materials','MATERIALS_CP'),entry('Final readiness check')]},
 {id:'starter-light',family_id:'starter-light',name:'Light turn / refresh',version:1,archived:false,entries:[entry('Inspection and scope','TURN_INSPECT',true),entry('Small repair punch list','LABOR_STD',false,'60'),entry('Selective touch-up','PAINT_WALL'),entry('Cleaning','CLEAN_STD'),entry('Safety and final readiness')]},
 {id:'starter-visit',family_id:'starter-visit',name:'Maintenance visit / punch list',version:1,archived:false,entries:[entry('Maintenance visit','SVC_MIN',true,'60'),entry('Additional approved scope'),entry('Materials','MATERIALS_CP')]}
];
export function validateTemplateEntries(entries:unknown):TemplateEntry[]{if(!Array.isArray(entries)||entries.length>100)throw new Error('Template must have at most 100 entries');return entries.map(e=>{if(!e||typeof e.description!=='string'||e.description.length>1000)throw new Error('Each template entry needs a description');return {item_code:String(e.item_code??'').slice(0,100),description:e.description,qty:String(e.qty??'1'),minutes:String(e.minutes??''),material_cost:'',room:String(e.room??'').slice(0,100),included:e.included===true};});}
