'use client';
import { useState } from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import { TEMPLATES, assignmentStatus, completeTask, releaseAssignment, releaseIssues, setWaiting, resumeAssignment, completeWorkOrder, addWorkOrder, localDay, type Person, type Row, type Sheet } from '@/lib/habu-paper/model';
import { ROLES, STAGES, inbox, newReview, scheduleProposal, targetDate, timing, type ReviewSheet } from '@/lib/habu-paper/review';

const stamp = (at: string) => Number.isFinite(Date.parse(at)) ? new Date(at).toLocaleString('en-US', { timeZone: 'America/Los_Angeles', dateStyle: 'medium', timeStyle: 'short' }) : at;
export default function WorkflowReview({ initial }: { initial: ReviewSheet[] }) {
  const [sheets, setSheets] = useState(initial), [role, setRole] = useState<Person>('alex');
  const [view, setView] = useState<'inbox' | 'all' | 'sheet'>('inbox'), [selected, setSelected] = useState(initial[0].id), [step, setStep] = useState('notice');
  const [whole, setWhole] = useState(true), [message, setMessage] = useState('');
  const [modal, setModal] = useState<'schedule' | 'wait' | 'new' | 'na' | null>(null);
  const [naRow, setNaRow] = useState<Row | null>(null);
  const [keys, setKeys] = useState(''), [mode, setMode] = useState<'standard' | 'remodel'>('standard'), [end, setEnd] = useState(''), [reason, setReason] = useState(''), [follow, setFollow] = useState(''), [address, setAddress] = useState(''), [work, setWork] = useState('');
  const today = localDay(new Date()), sheet = sheets.find(s => s.id === selected)!;
  const stage = STAGES.find(a => a.id === step)!, state = sheet.assignments[step], status = assignmentStatus(sheet, step);
  const mine = state.owner === role, canEdit = mine && status === 'ready';
  const proposal = keys <= today ? scheduleProposal(sheet, keys, mode, end, reason) : null;
  function update(fn: (s: ReviewSheet) => Sheet) { setSheets(all => all.map(s => s.id === selected ? { ...s, ...fn(s) } : s)); }
  function open(s: ReviewSheet, id: string) { setSelected(s.id); setStep(id); setView('sheet'); setMessage(''); }
  function changeRole(value: Person) { setRole(value); setView('inbox'); }
  function edit(row: Row, value: string) {
    update(s => ({ ...s, values: { ...s.values, [row.id]: value } }));
  }
  function field(row: Row) {
    const owned = row.assignment ? sheet.assignments[row.assignment].owner === role && assignmentStatus(sheet, row.assignment) === 'ready' : role === 'alex';
    const active = row.assignment === step;
    const recorded = sheet.tasks[row.id];
    return <div className={`wr-field ${active ? 'wr-highlight' : ''}`} key={row.id}>
      {row.type === 'task' ? <><label><input type="checkbox" checked={!!recorded} disabled={!owned || !!recorded} onChange={() => update(s => completeTask(s, row.id, role, new Date().toISOString()))} />{row.label}</label>{recorded && <small>{recorded.outcome === 'na' ? `N/A: ${recorded.reason}` : '✓'} · {ROLES[recorded.actor] || 'Sample role'} · {stamp(recorded.at)}</small>}{owned && !recorded && <button className="wr-na" onClick={() => { setNaRow(row); setReason(''); setModal('na'); }}>N/A</button>}</> : <label>{row.label}{row.required ? ' *' : ''}{row.id === 'keys-returned' ? <><input type="date" value={sheet.values[row.id] || ''} readOnly /><small>Use “Set turn schedule” to record keys and review deadlines.</small></> : row.type === 'choice' ? <select disabled={!owned} value={sheet.values[row.id] || ''} onChange={e => edit(row, e.target.value)}><option value="">Choose…</option>{row.options?.map(o => <option key={o}>{o}</option>)}</select> : <input disabled={!owned} type={row.type === 'money' || row.type === 'number' ? 'number' : row.type} min={row.type === 'money' || row.type === 'number' ? 0 : undefined} value={sheet.values[row.id] || ''} onChange={e => edit(row, e.target.value)} />}</label>}
    </div>;
  }
  function list(kind: 'ready' | 'upcoming' | 'waiting', title: string, description: string) {
    const items = inbox(sheets, role, kind, today);
    return <section className="wr-list"><header><h2>{title} <span>{items.length}</span></h2><p>{description}</p></header>{items.length ? items.map(({ sheet: s, stage: a }) => {
      const v = s.assignments[a.id], late = v.due && v.due < today;
      return <button className="wr-item" key={s.id + a.id} onClick={() => open(s, a.id)}><div><strong>{a.label}</strong><p>{s.values.address}</p><small>{s.id} · {s.priority} priority</small>{kind === 'upcoming' && <p className="wr-dependency">Waiting for {a.needs.filter(n => !s.assignments[n].released).map(n => `${STAGES.find(x => x.id === n)!.label} (${ROLES[s.assignments[n].owner]})`).join(' + ')}</p>}{kind === 'waiting' && <p>{v.waiting?.reason} · <b>{v.waiting!.followUp < today ? 'Follow-up overdue' : 'Follow up'} {v.waiting?.followUp}</b></p>}</div><div className={late ? 'wr-late' : 'wr-timing'}><b>{timing(s, a.id, today)}</b><span>{v.due || 'Needs a due date'}</span><small>Open master sheet →</small></div></button>;
    }) : <p className="wr-empty">Nothing here for {ROLES[role]}.</p>}</section>;
  }
  return <main className="wr-app">
    <header className="wr-top"><div><p className="wr-eyebrow">HABU · WORKFLOW REVIEW</p><h1>{view === 'inbox' ? 'My Work' : view === 'all' ? 'Active workflows' : sheet.values.address}</h1><p>One shared sheet. Everyone knows their next step.</p></div><label>Review as role<select value={role} onChange={e => changeRole(e.target.value as Person)}>{Object.entries(ROLES).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label></header>
    <div className="wr-demo">Owner-only review · Fictional properties · Role switching simulates staff inboxes · Changes reset on refresh</div>
    <nav className="wr-nav"><button aria-pressed={view === 'inbox'} onClick={() => setView('inbox')}>My Work</button><button aria-pressed={view === 'all'} onClick={() => setView('all')}>Active workflows</button><Link href="/admin/habu-paper/forms">Form library ↗</Link><button className="wr-primary" onClick={() => { setAddress(''); setModal('new'); }}>+ Start vacancy</button></nav>
    <p role="status" className="wr-status">{message}</p>
    {view === 'inbox' && <><div className="wr-summary"><div><strong>{ROLES[role]}</strong><p>Urgent priority first, then high and normal; overdue and earliest due first within each priority.</p></div><span>{today} · Pacific time</span></div>{list('ready', 'Ready for you', 'Work you can act on now.')}{list('upcoming', 'Coming to you soon', 'Assigned to you already; becomes ready when the preceding steps are handed off.')}{list('waiting', 'Waiting & follow-ups', 'Still yours to follow up. Dependencies and due dates stay visible.')}</>}
    {view === 'all' && <section className="wr-list"><header><h2>Vacancy workflows</h2><p>Each run has its own sheet, assignments and history.</p></header>{sheets.map(s => <button className="wr-item" key={s.id} onClick={() => open(s, STAGES.find(a => s.assignments[a.id].owner === role && assignmentStatus(s, a.id) === 'ready')?.id || 'notice')}><div><strong>{s.values.address}</strong><p>{s.id} · {Object.values(s.assignments).filter(a => a.released).length}/{STAGES.length} assignments complete</p></div><div className="wr-timing"><b>{s.assignments.verify.released ? 'Property ready' : targetDate(s) && targetDate(s) < today ? 'Ready target overdue' : 'Ready target'}</b><span>{targetDate(s) || 'Awaiting keys'}</span></div></button>)}</section>}
    {view === 'sheet' && <>
      <section className="wr-milestone"><div><small>{sheet.schedule.mode === 'remodel' ? 'MAJOR REMODEL' : 'STANDARD TURN · 10 CALENDAR DAYS'}</small><h2>{sheet.assignments.verify.released ? 'Property verified ready' : targetDate(sheet) ? `Ready by ${targetDate(sheet)}` : 'Clock starts after keys return'}</h2><p>Keys: {sheet.values['keys-returned'] || 'not returned'} · Next day is Day 1 · Weekends and holidays count.</p>{sheet.schedule.reason && <p>Extension: {sheet.schedule.reason}</p>}</div><button onClick={() => { setKeys(sheet.values['keys-returned'] || today); setMode(sheet.schedule.mode); setEnd(sheet.schedule.target); setReason(sheet.schedule.reason); setModal('schedule'); }}>Set turn schedule</button><label>Workflow priority<select value={sheet.priority} onChange={e => update(s => ({ ...s, priority: e.target.value as ReviewSheet['priority'] }))}>{['Normal', 'High', 'Urgent'].map(v => <option key={v}>{v}</option>)}</select></label></section>
      <div className="wr-workspace"><aside className="wr-route"><h2>Steps & routing</h2><p>2–4 roles · parallel work allowed</p>{STAGES.map((a, i) => { const v = sheet.assignments[a.id], st = assignmentStatus(sheet, a.id); return <button aria-pressed={step === a.id} className={`wr-stop ${st}`} key={a.id} onClick={() => { setStep(a.id); setMessage(''); }}><span className="wr-dot">{st === 'done' ? '✓' : i + 1}</span><div><strong>{a.label}</strong><small>{ROLES[v.owner]} · {st === 'upcoming' ? 'Coming soon' : st}</small><small className={v.due && v.due < today && st !== 'done' ? 'wr-late' : ''}>{st === 'done' ? 'Completed' : v.due || 'Date to set'}</small></div></button>; })}<p>Accounting runs alongside the turn. Its due date is set separately.</p><Link href="/admin/habu-paper">Earlier paper / route demo ↗</Link></aside>
      <div><section className="wr-action"><p className="wr-eyebrow">{mine ? 'YOUR ASSIGNMENT' : `WITH ${ROLES[state.owner]}`} · {timing(sheet, step, today)}</p><h2>{stage.label}</h2><div className="wr-controls"><label>Assigned role<select disabled={status === 'done'} value={state.owner} onChange={e => { const owner = e.target.value as Person; update(s => ({ ...s, assignments: { ...s.assignments, [step]: { ...s.assignments[step], owner } }, history: [...s.history, { id: crypto.randomUUID(), actor: role, at: new Date().toISOString(), text: `Review reassignment: ${stage.label} → ${ROLES[owner]}` }] })); }}>{Object.entries(ROLES).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Due date<input type="date" disabled={status === 'done'} value={state.due} onChange={e => update(s => ({ ...s, assignments: { ...s.assignments, [step]: { ...s.assignments[step], due: e.target.value } } }))} /></label></div>
        {status === 'upcoming' && <p>Waiting for {stage.needs.filter(n => !sheet.assignments[n].released).map(n => `${STAGES.find(a => a.id === n)!.label} · ${ROLES[sheet.assignments[n].owner]}`).join(' and ')}. You can review the full sheet now.</p>}
        {!mine && status !== 'done' && <button onClick={() => setRole(state.owner)}>Review as {ROLES[state.owner]}</button>}
        {status === 'done' && <p>Completed by {ROLES[state.released!.actor]} · {stamp(state.released!.at)}</p>}
        {mine && status === 'waiting' && <><p>{state.waiting?.reason} · Follow up {state.waiting?.followUp}</p><button onClick={() => update(s => resumeAssignment(s, step, role, new Date().toISOString()))}>Resume work</button></>}
        {canEdit && <><p>{releaseIssues(sheet, step).length ? `Before handoff: ${releaseIssues(sheet, step).join('; ')}.` : 'Required checks complete. Ready to hand off.'}</p><div className="wr-buttons"><button className="wr-primary" disabled={releaseIssues(sheet, step).length > 0} onClick={() => { update(s => releaseAssignment(s, step, role, new Date().toISOString())); setMessage(`${stage.label} completed. Eligible next steps are now in the assigned roles’ Ready inboxes.`); }}>Complete & hand off →</button><button onClick={() => { setReason(''); setFollow(today); setModal('wait'); }}>Waiting on someone</button></div></>}
      </section>
      <div className="wr-sheet-toggle"><button aria-pressed={whole} onClick={() => setWhole(true)}>Whole master sheet</button><button aria-pressed={!whole} onClick={() => setWhole(false)}>My selected section</button><span>Highlighted lines belong to this step</span></div>
      <article className="wr-paper"><header><small>HIGH DESERT PROPERTY MANAGEMENT</small><h2>Vacancy Tracking</h2><p>Gold master sheet · {sheet.id}</p></header>{whole && <div className="wr-fields">{TEMPLATES.vacancy.header.map(field)}</div>}<div className={whole ? 'wr-columns' : ''}>{(whole ? ['left', 'right', 'back'] : ['selected']).map(column => <div className="wr-paper-column" key={column}>{TEMPLATES.vacancy.sections.filter(s => whole ? s.column === column : s.rows.some(r => r.assignment === step)).map(s => <section className="wr-paper-section" key={s.id}><h3>{s.label}</h3>{s.rows.filter(r => whole || r.assignment === step).map(field)}</section>)}</div>)}</div>
      {(whole || ['inspection', 'turn-work', 'verify'].includes(step)) && <section className="wr-paper-section"><h3>BACK OF SHEET · WORK ORDERS</h3>{sheet.workOrders.map(w => <label className="wr-workorder" key={w.id}><input type="checkbox" checked={!!w.completed} disabled={sheet.assignments['turn-work'].owner !== role || assignmentStatus(sheet, 'turn-work') !== 'ready' || !!w.completed} onChange={() => update(s => completeWorkOrder(s, w.id, role, new Date().toISOString()))} />{w.description}{w.completed && <small> · {ROLES[w.completed.actor]} · {stamp(w.completed.at)}</small>}</label>)}{!sheet.workOrders.length && <p>No work orders recorded.</p>}{(role === 'alex' || role === sheet.assignments.inspection.owner) && !sheet.assignments['turn-work'].released && <form className="wr-controls" onSubmit={e => { e.preventDefault(); update(s => addWorkOrder(s, work, role, new Date().toISOString())); setWork(''); }}><label>Work discovered during inspection<input value={work} onChange={e => setWork(e.target.value)} required /></label><button disabled={!work.trim()}>Add work order</button></form>}</section>}</article>
      <details className="wr-history"><summary>Completion & handoff history ({sheet.history.length})</summary>{sheet.history.length ? sheet.history.map(h => <p key={h.id}>{h.text}<small>{ROLES[h.actor]} · {stamp(h.at)}</small></p>) : <p>No new actions in this review yet.</p>}</details>
      </div></div>
    </>}
    {modal && <Dialog.Root open onOpenChange={open => !open && setModal(null)}><Dialog.Portal><Dialog.Overlay className="wr-overlay" /><Dialog.Content className="wr-dialog" aria-describedby={undefined}><Dialog.Close className="wr-close" aria-label="Close dialog">×</Dialog.Close><Dialog.Title>{modal === 'schedule' ? 'Review suggested dates' : modal === 'new' ? 'Start a vacancy workflow' : modal === 'na' ? 'Mark not applicable' : 'Waiting & follow-up'}</Dialog.Title>
      {modal === 'na' && <><p>{naRow?.label}</p><label>Reason<input autoFocus value={reason} onChange={e => setReason(e.target.value)} /></label><button className="wr-primary" disabled={!reason.trim()} onClick={() => { if (naRow) update(s => completeTask(s, naRow.id, role, new Date().toISOString(), 'na', reason)); setModal(null); }}>Record N/A</button></>}
      {modal === 'new' && <form onSubmit={e => { e.preventDefault(); const s = newReview(`VT-DEMO-${sheets.length + 1}`, address.trim(), today); setSheets(all => [...all, s]); setRole('alex'); open(s, 'notice'); setModal(null); }}><label>Example property address<input autoFocus required value={address} onChange={e => setAddress(e.target.value)} /></label><p>Starts with Front Desk. Later assignments use Property Manager, Maintenance and Accounting roles.</p><button className="wr-primary" disabled={!address.trim()}>Create review workflow</button></form>}
      {modal === 'wait' && <><label>What are you waiting for?<input autoFocus value={reason} onChange={e => setReason(e.target.value)} /></label><label>Follow-up date<input type="date" value={follow} onChange={e => setFollow(e.target.value)} /></label><button className="wr-primary" disabled={!reason.trim() || !follow} onClick={() => { update(s => setWaiting(s, step, role, reason, follow, new Date().toISOString())); setModal(null); }}>Move to Waiting</button></>}
      {modal === 'schedule' && <><label>Keys returned (Day 0)<input autoFocus type="date" max={today} value={keys} onChange={e => setKeys(e.target.value)} /></label><label>Turn type<select value={mode} onChange={e => setMode(e.target.value as 'standard' | 'remodel')}><option value="standard">Standard · 10 calendar days</option><option value="remodel">Major remodel · extended target</option></select></label>{mode === 'remodel' && <><label>Extended ready date<input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label><label>Reason for major remodel<input value={reason} onChange={e => setReason(e.target.value)} /></label></>}
      <p>Day 1 is the day after keys return. Weekends and holidays count. Proposed intermediate milestones: inspection Day 1, work complete Day 8, verified ready Day 10.</p>{proposal ? <><table><thead><tr><th>Milestone</th><th>Current</th><th>Suggested</th></tr></thead><tbody>{['keys', 'inspection', 'turn-work', 'verify'].map(id => <tr key={id}><td>{STAGES.find(a => a.id === id)!.label}{sheet.assignments[id].released ? ' (completed)' : ''}</td><td>{sheet.assignments[id].due || '—'}</td><td>{proposal.assignments[id].due || '—'}</td></tr>)}</tbody></table><p><b>Ready target: {targetDate(proposal)}</b>. Applying replaces due dates on open turn steps shown above. Completed step dates and accounting dates remain unchanged.</p></> : <p>Enter a key return date on or before today. Major remodels require a reason and a target later than the standard Day 10.</p>}<button className="wr-primary" disabled={!proposal || !!sheet.assignments.verify.released} onClick={() => { if (proposal) { update(s => ({ ...proposal, history: [...s.history, { id: crypto.randomUUID(), actor: role, at: new Date().toISOString(), text: `Schedule applied: keys ${keys}; ready ${targetDate(proposal)}; ${mode}${reason ? ` — ${reason}` : ''}` }] })); setModal(null); setMessage('Suggested turn dates applied. Key receipt still needs its checks and handoff.'); } }}>Apply reviewed dates</button></>}
    </Dialog.Content></Dialog.Portal></Dialog.Root>}
  </main>;
}
