// Text transcribed from user-provided OneDrive masters; not a legal validation.
export const ORIGINAL_TEXT = {
  "depositAgreement": "Owner / Agent is charging this Deposit for the purpose of securing the execution of a rental agreement after having approved the application and prior to entering into a rental agreement. If a rental agreement is executed, the Owner/Agent shall either apply the deposit towards the funds due under the rental agreement or refund the deposit immediately to the Tenant. If a rental agreement is not executed due to a failure by the applicant to comply with this agreement, the Owner/Agent may retain the deposit in full, unless the applicant has rejected the agreement due to the discovery of material defects relating to the premise’s habitability, as described in ORS 90.320(1). It is agreed that the tenant shall pay the balance of funds due by the date the property is to be occupied and sign a rental/lease agreement. If the unit has not been viewed by the applicant prior to lease up, dissatisfaction with the unit type, condition or location is not a cause for refund of the Deposit to Hold except for material defects relating to the premise’s habitability as described in ORS 90.320(1). If a rental agreement is not executed due to a failure by the Owner/Agent to comply with this Agreement, or if prior to entering the rental agreement the applicant rejects the unit due to a discovery of material defects relating to the premise’s habitability as described in ORS 90.320(1), within five (5) business days the Owner/Agent shall return the Deposit to the applicant either at the Owner/Agent’s place of business or by mailing the Deposit by First Class Mail.",
  "noticeTerms": "30 DAY NOTICE PERIOD STARTS THE DAY HIGH DESERT PROPERTY MANAGEMENT RECEIVES THE NOTICE.\n\nI/We hereby give thirty (30) days’ notice to vacate the premises on [vacate date]. Per the Rental Agreement, this notice is effective for all Tenants of this property. If the Tenant(s) remains in possession without the Landlord/Agent’s consent after the expiration of the term of the Lease or its termination, the Landlord/Agent may bring legal action for possession. Tenant(s) could be liable for court costs, and prevailing fees and have an eviction listed on their rental reference and/or Credit Report.\n\nIt is agreed and understood that the premises may be shown at reasonable times prior to the expiration of this notice after the Landlord/Agent issues appropriate notice to enter. Tenant(s) hereby certifies that payments of all utilities are current and tenants will continue to pay utility fees until the date keys are returned to High Desert Property Management at the office.\n\nOwner/Agent will write one check payable jointly to all Tenants. Tenants should agree among themselves on how to split up any security deposit refund. Owner/Agent may deduct for any damages or monetary defaults caused or allowed by Tenants and/or Tenants’ guests from the beginning of the tenancy until possession is returned to Owner/Agent, regardless of the move-in and move-out dates of Tenants. Tenant Property: All tenants agree that all personal belongings left on the premises of the property may be sold or disposed of by the Landlord without complying with the requirements of ORS 90.425(1) to (27).\n\nThis notice is for ALL tenants and all tenants have signed below.",
  "acknowledgments": [
    "Tenant is responsible for landscape maintenance to include mowing, watering, weeding and turning on irrigation in the Spring. Irrigation winterization blowouts will be coordinated by High Desert. (Section 4 Rental Agmt)",
    "Tenant acknowledges smoke alarm / carbon monoxide detector care & reset instructions. (Section 6 Rental Agmt)",
    "Tenant acknowledges that furnace filters are a tenant responsibility and their expense. Units with heat pumps must be turned to emergency heat when outside temperatures drop below 20 degrees. (Section 11 Rental Agmt)",
    "Tenant acknowledges that they are responsible for cleaning the cadet heaters twice a year and/or mini-split filter monthly. (Section 11 of Rental Agmt)",
    "New Tenant Inspection Form (property condition has been received and must be submitted through tenant portal to High Desert Property Management within 7 days of move-in date.",
    "Tenants must submit maintenance requests through the tenant portal. (Section 8.4 Rental Agmt)"
  ],
  "insurance": "If checked, Renter’s Insurance is required. Tenant is required to maintain a minimum of $100,000 liability coverage and add High Desert Property Management as an Interested Party. If Tenant(s) combined household income falls at or below 50% of the median income for the area, Renter’s Insurance may not be required.",
  "hoa": "If checked, there are move-in or move-out fees that are associated with this unit that are the Tenant’s responsibility to pay Owner/Agent within 30 days once the bill is assessed by the HOA or COA. The current fees are $0.00.",
  "mailbox": "If checked, the mail receptacle associated with the dwelling unit may be a locking type. Tenant(s) are solely responsible for the fees charged by the Postmaster for the re-keying of the box should a key not be provided by High Desert Property Management, or if the mailbox has not been re-keyed between tenancies.",
  "utility": "If checked, there is a monthly utility charge associated with this unit. After assessment of the monthly charge, Tenant(s) have thirty (30) days to pay the charge in full. Failure to pay the utility charge by the due date will result in a $50.00 non-compliance fee.",
  "fees": "Owner/Agent may also charge the following non-compliance fees:\n• Late payment of rent charge of $100.00.\n• Smoke alarm and carbon monoxide alarm tampering fee of $250.00.\n• Dishonored check fee of $35.00 plus the amount charged by the bank.\n• Early termination of lease fee not to exceed 1-1/2 times the monthly rent, or actual damages at the option of High Desert Property Management.\n• Owner / Agent may charge the following non-compliance fees after first giving a written warning notice of the initial violation if non-compliance occurs within one year: $50.00 fee for 2nd violation, and $50.00 plus 5% of current rent for each subsequent violation. 1. Failure to clean up animal waste, garbage, rubbish, or other waste fee. 2. Parking violation or other improper use of vehicle fee.\n• Owner/Agent may charge a fee for keeping an unauthorized pet capable of causing damage, that is not removed within 48 hours of written warning notice. Fee not to exceed $250.00 per violation.\n• Owner/Agent may charge a fee for smoking/vaping in a designated non-smoking/vaping unit or area of the property. A fee may be assessed for repeat violations that occur as early as 24 hours after the effective date of a written warning notice and for each subsequent violation within one year. Fee not to exceed $250.00 per violation."
} as const;
