"use client";
import { useCallback, useEffect, useState } from 'react';
import { CAPABILITIES, effectiveCapabilities, roleCapabilities, type Capabilities, type Capability } from '@/lib/staff-capabilities';
type Staff={person:string;email:string|null;active:boolean;access_role:string;overrides:Partial<Capabilities>;version:number;capabilities:Capabilities};
type Audit={id:number;person:string;actor:string;reason:string;created_at:string;before_overrides:Partial<Capabilities>;after_overrides:Partial<Capabilities>};
export default function StaffPermissions(){
 const [staff,setStaff]=useState<Staff[]>([]),[audit,setAudit]=useState<Audit[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<Staff|null>(null),[overrides,setOverrides]=useState<Partial<Capabilities>>({}),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/staff-permissions',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setStaff(d.staff);setAudit(d.audit);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 function choose(s:Staff){setSelected(s);setOverrides({...s.overrides});setReason('');setError('');setNotice('');}
 function change(key:Capability,value:string){setOverrides(old=>{const next={...old};if(value==='default')delete next[key];else next[key]=value==='on';return next;});}
 async function save(){if(!selected)return;setBusy(true);setError('');try{const r=await fetch('/api/admin/staff-permissions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({person:selected.person,version:selected.version,overrides,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelected(null);setNotice(`Permissions saved for ${selected.person}. Server checks use the new permissions immediately; ask them to refresh their page.`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const preview=selected?effectiveCapabilities(selected.access_role,selected.active,overrides):null;
 return <main className="w-full min-w-0 space-y-6 p-4 md:p-8">
  <div><h1 className="text-3xl font-semibold">Staff permissions</h1><p className="mt-2 text-sm text-charcoal-500">Control invoice, estimate, and template capabilities for each staff member. Roles and other application permissions are unchanged.</p></div>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-lg bg-green-50 p-4 text-green-800">{notice}</p>}
  <div className="flex gap-3"><input className="min-h-11 flex-1 rounded-lg border p-3" aria-label="Search staff" placeholder="Find staff by name or email" value={search} onChange={e=>setSearch(e.target.value)}/><button className="rounded-lg border px-4" disabled={loading||busy} onClick={()=>{setSelected(null);setError('');void load();}}>Refresh</button></div>
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-sand-50"><tr><th className="p-3">Staff</th><th className="p-3">Role</th>{CAPABILITIES.map(c=><th key={c.key} className="p-3">{c.label}</th>)}<th className="p-3">Manage</th></tr></thead><tbody>
   {staff.filter(s=>`${s.person} ${s.email}`.toLowerCase().includes(search.toLowerCase())).map(s=><tr key={s.person} className="border-t"><td className="p-3"><strong>{s.person}</strong><div className="text-xs text-charcoal-500">{s.email}{!s.active&&' · Inactive'}</div></td><td className="p-3">{s.access_role}</td>{CAPABILITIES.map(c=><td className="p-3" key={c.key}><span className={s.capabilities[c.key]?'text-green-800':'text-charcoal-400'}>{s.capabilities[c.key]?'On':'Off'}</span><div className="text-xs text-charcoal-400">{!s.active?'Inactive':s.access_role==='admin'?'Administrator':s.overrides[c.key]===undefined?'Role default':'Override'}</div></td>)}<td className="p-3"><button className="min-h-10 rounded-lg border px-3 disabled:opacity-40" disabled={!s.active||s.access_role==='admin'||busy} onClick={()=>choose(s)}>Edit {s.person}</button></td></tr>)}
  </tbody></table>{loading&&<p role="status" className="p-4">Loading permissions…</p>}</div>
  {selected&&<section aria-label={`Permissions for ${selected.person}`} className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Permissions for {selected.person}</h2><p className="mt-2 text-sm text-charcoal-500">Choose Role default to remove an override. PDF generation requires invoice drafts. Templates and issuing require estimate drafts. Administrator access stays controlled by the administrator role.</p>
   <div className="my-4 divide-y">{CAPABILITIES.map(c=><div key={c.key} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="max-w-xl"><label htmlFor={c.key} className="font-medium">{c.label}</label><p className="text-sm text-charcoal-500">{c.description}</p></div><div className="flex items-center gap-3"><select id={c.key} className="min-h-11 rounded-lg border p-2" value={overrides[c.key]===undefined?'default':overrides[c.key]?'on':'off'} onChange={e=>change(c.key,e.target.value)}><option value="default">Role default ({roleCapabilities(selected.access_role)[c.key]?'On':'Off'})</option><option value="on">On</option><option value="off">Off</option></select><span className="text-sm">Effective: {preview?.[c.key]?'On':'Off'}</span></div></div>)}</div>
   <label className="block text-sm">Reason for change<textarea className="mt-1 w-full rounded-lg border p-3" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} placeholder="Why is this access changing?"/></label><div className="mt-4 flex gap-3"><button disabled={busy||reason.trim().length<3} onClick={()=>void save()} className="min-h-11 rounded-lg bg-charcoal-900 px-5 text-white disabled:opacity-40">{busy?'Saving…':'Save permissions'}</button><button disabled={busy} className="rounded-lg border px-5" onClick={()=>setSelected(null)}>Cancel</button></div></section>}
  <section><h2 className="text-xl font-semibold">Recent changes</h2><p className="mb-3 text-sm text-charcoal-500">Latest 100 changes. Restore Role default or a previous setting to reverse a change.</p><div className="space-y-3">{audit.length===0&&<p className="text-sm">No permission changes recorded yet.</p>}{audit.map(a=><div key={a.id} className="rounded-lg border bg-white p-4 text-sm"><strong>{a.person}</strong> · {a.actor} · {new Date(a.created_at).toLocaleString()}<p>{a.reason}</p><ul className="mt-2 text-xs text-charcoal-500">{CAPABILITIES.filter(c=>a.before_overrides[c.key]!==a.after_overrides[c.key]).map(c=><li key={c.key}>{c.label}: {a.before_overrides[c.key]===undefined?'Role default':a.before_overrides[c.key]?'On':'Off'} → {a.after_overrides[c.key]===undefined?'Role default':a.after_overrides[c.key]?'On':'Off'}</li>)}</ul></div>)}</div></section>
 </main>;
}
