'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {pacificDay,shiftDay} from '@/lib/maintenance-workspace/model';
import {weekStartPacific} from '@/lib/eos/scorecard';
import type {DaySummary,Issue,WorkRecord} from '@/lib/daily-billing/model';
import {ReportPeriodPresets} from '../invoices/report-period-presets';
import './review.css';
type Data={office:boolean;admin:boolean;person:string;technician:string;migrationReady:boolean;warnings:string[];lastBillSync:string|null;days:DaySummary[];issues:Issue[];records:WorkRecord[];staff:{person:string;name:string}[];workOrders:{id:string;wo_number:string|null;property_name:string|null;description:string|null}[];tasks:{id:string;job_id:string;description:string}[];jobs:{id:string;work_order_id:string;property_name:string}[];counts:{active:number;deferred:number}};
type Editor={kind:'record';id:string;record?:WorkRecord}|{kind:'review';record:WorkRecord}|{kind:'decision';issue:Issue};
const hours=(n:number|null|undefined)=>n==null?'—':`${n.toFixed(2).replace(/\.00$/,'')} h`;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const pretty=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',weekday:'short',timeZone:'UTC'});
const kinds:Record<string,string>={no_invoice:'Completed work',ready:'Billing coverage',draft:'Draft invoices',posting:'AppFolio posting',data_quality:'Missing details',review:'Work review',in_progress:'In progress',credit_review:'Credits'};
export default function DailyBillingReview({embedded=false}:{embedded?:boolean}){
 const params=useSearchParams();const initial=params.get('date');const thisWeek=weekStartPacific(new Date());
 const [from,setFrom]=useState(initial||thisWeek),[to,setTo]=useState(initial||shiftDay(thisWeek,6)),[tech,setTech]=useState('');
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 const [view,setView]=useState<'list'|'calendar'>('list'),[day,setDay]=useState<string|null>(initial),[kind,setKind]=useState(''),[history,setHistory]=useState(false),[editor,setEditor]=useState<Editor|null>(null),[search,setSearch]=useState('');
 const generation=useRef(0);
 const load=useCallback(async()=>{const gen=++generation.current;setLoading(true);setError('');try{const r=await fetch(`/api/maintenance/daily-billing?from=${from}&to=${to}&technician=${encodeURIComponent(tech)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);if(gen===generation.current)setData(d);}catch(e){if(gen===generation.current)setError((e as Error).message);}finally{if(gen===generation.current)setLoading(false);}},[from,to,tech]);
 useEffect(()=>{void load();return()=>{generation.current++}},[load]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editor||!data)return;setBusy(true);setError('');const f=new FormData(event.currentTarget);const value=(k:string)=>String(f.get(k)||'');
  let body:Record<string,unknown>;
  if(editor.kind==='record')body={op:'record',id:editor.id,version:editor.record?.version,technician:editor.record?.technician||value('technician')||data.person,work_order_id:editor.record?.work_order_id||value('work_order_id')||null,work_date:value('work_date'),minutes:Number(value('minutes')),activity_kind:value('activity_kind'),progress:value('progress'),note:value('note'),materials:value('materials'),status:value('status')};
  else if(editor.kind==='review')body={op:'review',id:editor.record.id,version:editor.record.version,status:value('status'),billability:value('billability'),note:value('note'),review_due:value('review_due')||null};
  else body={op:'disposition',issue_key:editor.issue.key,disposition:value('disposition'),owner:value('owner'),review_on:value('review_on'),note:value('note')};
  try{if(body.op==='record'&&body.activity_kind==='job'&&!body.work_order_id)throw new Error('Choose a work order for project activity.');const r=await fetch('/api/maintenance/daily-billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setEditor(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const issues=(data?.issues||[]).filter(i=>(history||!i.decision||i.overdue)&&(!day||i.day===day)&&(!kind||i.kind===kind));
 const records=(data?.records||[]).filter(r=>!day||r.work_date===day);
 const totals=(data?.days||[]).reduce((n,d)=>({project:n.project+d.projectHours,other:n.other+d.otherHours,draft:n.draft+(d.draftHours||0),issued:n.issued+(d.issuedHours||0),labor:n.labor+(d.issuedLabor||0)}),{project:0,other:0,draft:0,issued:0,labor:0});
 const addRecord=()=>{setSearch('');setEditor({kind:'record',id:crypto.randomUUID()});setError('');};
 function recordTitle(r:WorkRecord){const task=data?.tasks.find(t=>t.id===r.task_id);const wo=data?.workOrders.find(w=>w.id===r.work_order_id);return task?.description||[wo?.property_name,wo?.wo_number].filter(Boolean).join(' · ')||r.activity_kind||'Activity';}
 return <main className={`db-review ${embedded?'db-embedded':''}`}>
  <header><div>{!embedded&&<Link href="/maintenance/invoices?tab=report">← Work & Billing</Link>}<h1>{data&&!data.office?'My daily closeout':'Daily Billing Review'}</h1><p>Account for the work, prepare the invoice, verify AppFolio posting.</p></div><div className="db-actions"><button onClick={()=>void load()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button><button className="db-primary" onClick={addRecord} disabled={!data?.migrationReady}>Log work / activity</button></div></header>
  {error&&<div role="alert" className="db-error">{error}</div>}
  {data?.warnings.map(w=><div role="status" className="db-warning" key={w}>{w}</div>)}
  <div className="db-filters"><label>From<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setDay(null)}}/></label><label>Through<input type="date" value={to} onChange={e=>{setTo(e.target.value);setDay(null)}}/></label>
   {data?.office&&<label>Technician<select value={tech} onChange={e=>setTech(e.target.value)}><option value="">All technicians</option>{data.staff.map(s=><option key={s.person} value={s.person}>{s.name||s.person}</option>)}</select></label>}
   <button onClick={()=>{setFrom(thisWeek);setTo(shiftDay(thisWeek,6));setDay(null)}}>This week</button><button onClick={()=>{setFrom(shiftDay(thisWeek,-7));setTo(shiftDay(thisWeek,-1));setDay(null)}}>Last week</button>
   <ReportPeriodPresets from={from} to={to} onChange={(a,b)=>{setFrom(a);setTo(b);setDay(null)}}/>
  </div>
  {data&&<>
   <div className="db-tiles"><article><small>Project activity logged</small><strong>{hours(totals.project)}</strong><span>Submitted/reviewed; actual work date</span></article><article><small>Other activity logged</small><strong>{hours(totals.other)}</strong><span>Travel, parts, shop and other time</span></article>{data.office&&<><article><small>Invoice labor hours</small><strong>{hours(totals.issued)}</strong><span>Issued · {hours(totals.draft)} still in drafts</span></article><article><small>Issued labor value</small><strong>{money(totals.labor)}</strong><span>Includes flat-price labor; not collected cash</span></article><article><small>Items to review</small><strong>{data.counts.active}</strong><span>{data.counts.deferred} decisions saved</span></article></>}</div>
   <p className="db-note">Work activity uses the actual work date. Invoice totals use completed date, with creation date fallback; they may land on a different day. Missing quantities are never estimated from dollars. A low invoice total alone does not prove missing billing.</p>
   {data.admin&&<p className="db-note">Admin-only: select a technician to compare timecards with logged activity. Scheduled defaults remain unconfirmed. “Unexplained” means worked time minus submitted activity, not automatically billable time.</p>}
   {data.office&&<section><div className="db-filters"><h3>Billing queue{day?` · ${pretty(day)}`:""}</h3><label>Show<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All review items</option>{Object.entries(kinds).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="db-check"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Include saved decisions</label></div>
    {!issues.length&&<p className="db-empty">No matching billing exceptions. Check the activity log and source warnings before treating the period as complete.</p>}
    <div className="db-stack">{issues.map(i=><article key={i.key} className="db-card"><div className="db-between"><h3>{i.title}</h3><span className={i.overdue?'db-overdue':'db-badge'}>{i.overdue?'Review due':i.decision?.disposition||kinds[i.kind]}</span></div><b>{i.property}</b><p>{i.day||'Date missing'}{i.person?` · ${i.person}`:''}</p><p>{i.detail}</p>{i.decision&&<p className="db-note">{i.decision.owner} · review {i.decision.review_on} · {i.decision.note}</p>}<div className="db-actions"><Link href={i.href}>Open record</Link>{i.kind==='posting'&&<Link href="/maintenance/invoices?tab=reconcile">Match AppFolio bill</Link>}{i.woId&&['no_invoice','ready'].includes(i.kind)&&<Link href={`/maintenance/invoices?from_wo=${i.woId}`}>Review / prepare invoice</Link>}<button disabled={!data.migrationReady} onClick={()=>{setError('');setEditor({kind:'decision',issue:i})}}>Record follow-up / decision</button></div></article>)}</div>
   </section>}
   <div className="db-between"><h2>Daily picture</h2><div className="db-actions"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>Daily list</button><button aria-pressed={view==='calendar'} onClick={()=>setView('calendar')}>Calendar</button></div></div>
   {view==='calendar'?<div className="db-calendar" aria-label="Daily billing calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(w=><b key={w}>{w}</b>)}{Array.from({length:(new Date(from+'T12:00:00Z').getUTCDay()+6)%7},(_,i)=><span key={`pad${i}`}/>)}{data.days.map(d=><button key={d.date} onClick={()=>setDay(d.date)} aria-pressed={day===d.date} className={!d.recordCount?'db-unknown':d.issueCount?'db-pending':'db-recorded'}><b>{pretty(d.date)}</b><span>Activity {hours(d.projectHours+d.otherHours)}</span>{data.office&&<><span>Issued {hours(d.issuedHours)} · {money(d.issuedLabor)}</span><span>Draft {hours(d.draftHours)}</span></>}<small>{!d.recordCount?'No activity log':`${d.issueCount} review items`}{d.incomplete?' · partial billing data':''}</small></button>)}</div>:<div className="db-table-wrap"><table><thead><tr><th>Day</th><th>Project</th><th>Other</th>{data.office&&<><th>Issued hours</th><th>Draft hours</th><th>Issued labor</th><th>Review</th></>}{data.admin&&tech&&<><th>Worked</th><th>Unconfirmed</th><th>Unexplained</th></>}</tr></thead><tbody>{data.days.map(d=><tr key={d.date}><td><button onClick={()=>setDay(d.date)}>{pretty(d.date)}</button>{!d.recordCount&&<small>No activity log</small>}</td><td>{hours(d.projectHours)}</td><td>{hours(d.otherHours)}</td>{data.office&&<><td>{hours(d.issuedHours)}{d.incomplete?' *':''}</td><td>{hours(d.draftHours)}</td><td>{money(d.issuedLabor)}</td><td>{d.issueCount}</td></>}{data.admin&&tech&&<><td>{hours(d.workedHours)}</td><td>{hours(d.scheduledHours)}</td><td>{hours(d.unexplainedHours)}</td></>}</tr>)}</tbody></table></div>}
   <div className="db-between"><h2>{day?`Details for ${pretty(day)}`:'Period details'}</h2>{day&&<button onClick={()=>setDay(null)}>Show all days</button>}</div>
   <section><div className="db-between"><h3>Work and activity log</h3><button onClick={addRecord} disabled={!data.migrationReady}>+ Add entry</button></div><div className="db-stack">{records.map(r=><article key={r.id} className="db-card"><div className="db-between"><h3>{recordTitle(r)}</h3><span className="db-badge">{r.status}</span></div><p>{r.work_date} · {r.technician} · {r.minutes} minutes · {r.progress} · {r.billability||'review'}</p><p>{r.note}</p>{r.review_note&&<p className="db-note">{r.review_owner}: {r.review_note}{r.review_due?` · review ${r.review_due}`:''}</p>}<div className="db-actions">{r.task_id?<Link href={data.office?'/maintenance/workspace':'/maintenance/field'}>Open project work log</Link>:['draft','returned'].includes(r.status)&&<button disabled={!data.migrationReady} onClick={()=>{setError('');setEditor({kind:'record',id:r.id,record:r})}}>Edit entry</button>}{data.office&&!r.task_id&&['submitted','held','reviewed'].includes(r.status)&&<button disabled={!data.migrationReady} onClick={()=>{setError('');setEditor({kind:'review',record:r})}}>Review work</button>}</div></article>)}</div>{!records.length&&<p className="db-empty">No work activity recorded for this selection. This is missing documentation, not proof that no work happened.</p>}</section>
   {data.office&&<p className="db-note">AppFolio snapshot: {data.lastBillSync?new Date(data.lastBillSync).toLocaleString('en-US',{timeZone:'America/Los_Angeles',timeZoneName:'short'}):'unavailable'}. Posting and payment are separate checks.</p>}
  </>}
  {editor&&data&&<div className="db-overlay"><section className="db-dialog" role="dialog" aria-modal="true" aria-labelledby="db-editor-title"><div className="db-between"><h2 id="db-editor-title">{editor.kind==='record'?'Daily work / activity':editor.kind==='review'?'Review work performed':'Billing follow-up'}</h2><button disabled={busy} onClick={()=>setEditor(null)}>Close</button></div>{error&&<p role="alert" className="db-error">{error}</p>}<form onSubmit={save}>
   {editor.kind==='record'?<>
    <label>Technician<select name="technician" defaultValue={editor.record?.technician||tech||data.person} disabled={!!editor.record||!data.office}>{data.staff.map(s=><option key={s.person} value={s.person}>{s.name||s.person}</option>)}</select></label>
    <label>Activity<select name="activity_kind" defaultValue={editor.record?.activity_kind||'job'}>{[['job','Project / work order'],['travel','Travel'],['parts','Parts run'],['shop','Shop / equipment'],['callback','Callback'],['other','Other']].map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
    {!editor.record&&<label>Find work order<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Property, work order or description"/></label>}
    <label>Work order (required for project work)<select name="work_order_id" defaultValue={editor.record?.work_order_id||''} disabled={!!editor.record}><option value="">No work order / other activity</option>{data.workOrders.filter(w=>editor.kind==='record'&&editor.record?w.id===editor.record.work_order_id:!search||`${w.property_name} ${w.wo_number} ${w.description}`.toLowerCase().includes(search.toLowerCase())).map(w=><option key={w.id} value={w.id}>{w.property_name} · {w.wo_number} · {w.description?.slice(0,80)}</option>)}</select></label>
    <div className="db-filters"><label>Date worked<input name="work_date" type="date" max={pacificDay()} defaultValue={editor.record?.work_date||day||pacificDay()} required/></label><label>Minutes spent<input name="minutes" type="number" min="1" max="960" step="1" defaultValue={editor.record?.minutes} required/></label></div>
    <label>Progress<select name="progress" defaultValue={editor.record?.progress||'done'}><option value="done">Done</option><option value="partial">Continuing</option><option value="blocked">Blocked</option></select></label>
    <label>What did you do?<textarea name="note" defaultValue={editor.record?.note} required/></label><label>Parts / receipt notes<textarea name="materials" defaultValue={editor.record?.materials}/></label>
    <label>Save as<select name="status" defaultValue="submitted"><option value="submitted">Submit for review</option><option value="draft">Unfinished draft</option></select></label><p className="db-note">Record actual time once. If already logged against a priced project task, use its existing work entry. This does not change your timecard or authorize a charge.</p>
   </>:editor.kind==='review'?<><p>{recordTitle(editor.record)} · {editor.record.minutes} minutes</p><label>Decision<select name="status" defaultValue="reviewed"><option value="reviewed">Reviewed</option><option value="held">Hold for follow-up</option><option value="returned">Return for correction</option></select></label><label>Billing treatment<select name="billability" defaultValue={editor.record.billability||'review'}><option value="review">Needs billing decision</option><option value="billable">Billable under approved scope</option><option value="nonbillable">Not billable</option></select></label><label>Reason / scope or invoice reference<textarea name="note" required defaultValue={editor.record.review_note}/></label><label>Follow-up date (required for hold)<input type="date" name="review_due" defaultValue={editor.record.review_due||shiftDay(pacificDay(),1)}/></label></>:<><p>{editor.issue.property} · {editor.issue.title}</p><label>Decision<select name="disposition" defaultValue={editor.issue.decision?.disposition||'deferred'}><option value="deferred">Follow up later</option><option value="not_billable">Not billable</option><option value="resolved">Verified / resolved</option></select></label><label>Responsible person<select name="owner" defaultValue={editor.issue.decision?.owner||data.person}>{data.staff.map(s=><option key={s.person} value={s.person}>{s.name||s.person}</option>)}</select></label><label>Review again on<input type="date" name="review_on" required defaultValue={editor.issue.decision?.review_on||shiftDay(pacificDay(),1)}/></label><label>Reason and evidence (invoice / AppFolio reference)<textarea name="note" required defaultValue={editor.issue.decision?.note}/></label><p className="db-note">This records a review decision. It does not create, issue or send an invoice. The item returns to the queue on its review date if the underlying exception remains.</p></>}
   <button className="db-primary" disabled={busy}>{busy?'Saving…':'Save'}</button>
  </form></section></div>}
 </main>;
}
